import { Video } from './models/Video';

/
 * AI Technology Application Types
 * This file contains TypeScript types and interfaces for the AI brand,
 * specifically tailored for the VidNexus application, which focuses on
 * creating AI-generated videos.
 * 
 * Brand Name: AI
 * Industry: Technology
 * Colors: Red, Orange, White
 */

export interface User {
    id: string;
    username: string;
    email: string;
    createdAt: Date;
}

/
 * Interface representing a video generated by the AI application.
 */
export interface AIVideo {
    id: string;
    title: string;
    description: string;
    creator: User;
    duration: number; // Duration in seconds
    resolution: string; // e.g., "1920x1080"
    createdAt: Date;
    updatedAt: Date;
    tags: string[];
    views: number;
    likes: number;
}

/
 * Interface representing the metadata for a collection of AI videos.
 */
export interface VideoCollection {
    id: string;
    title: string;
    description: string;
    videos: AIVideo[];
    createdAt: Date;
    updatedAt: Date;
}

/
 * Interface representing user interactions with the AI videos.
 */
export interface UserInteraction {
    userId: string;
    videoId: string;
    liked: boolean;
    viewedAt: Date;
}

/
 * Function to create a new video
 * @param title - Title of the video
 * @param description - Description of the video
 * @param creator - The user creating the video
 * @param duration - Duration of the video in seconds
 * @param resolution - Resolution of the video
 * @param tags - Tags associated with the video
 * @returns AIVideo - The newly created video object
 */
export function createVideo(
    title: string,
    description: string,
    creator: User,
    duration: number,
    resolution: string,
    tags: string[]
): AIVideo {
    const newVideo: AIVideo = {
        id: generateUniqueId(),
        title,
        description,
        creator,
        duration,
        resolution,
        createdAt: new Date(),
        updatedAt: new Date(),
        tags,
        views: 0,
        likes: 0
    };
    return newVideo;
}

/
 * Utility function to generate a unique identifier
 * @returns string - A unique identifier
 */
function generateUniqueId(): string {
    return 'video_' + Math.random().toString(36).substr(2, 9);
}

export { User, AIVideo, VideoCollection, UserInteraction };